#!/usr/bin/env ruby

# grab gems for all sub-scripts, without needing separate Gemfile
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'damerau-levenshtein', require: 'damerau-levenshtein'
  gem 'down', require: 'down'
  gem 'open3', require: "open3"
end

require_relative "find_unknown_value.rb"
require_relative "print_manual.rb"
require_relative "Commands.rb"

input_command = ARGV[0]

if input_command == nil
  print_manual
  return
end

matching_command = Commands::KNOWN_COMMANDS.find { |command|
  command.name == ARGV[0]
}

if matching_command == nil
  possible_commands = find_unknown_value(Commands::KNOWN_COMMAND_NAMES, input_command)
  unless possible_commands.empty?
    puts "Did you mean?"
    possible_commands.each do |command|
      puts "   " + command
    end
  end
  return
end

# strip command from ARGV and pass remaining
other_args = ARGV.drop(1)
matching_command.perform(*other_args) # convert array into arg list