#!/bin/bash

set -e

echo "Running all non-mutating (or easily reversible) commands"

ax launch_app com.google.android.GoogleCamera # most likely app to have
ax layout_bounds show
ax layout_bounds hide
ax list_packages
ax max_bright
ax permissions com.android.settings
ax pull_apks com.android.settings ~/temp
ax screenshot
ax settings_app
ax version_name
ax reboot