#!/bin/bash

set -e

printf "\nRunning all non-mutating (or easily reversible) commands:\n\n"

ax launch_app com.google.android.GoogleCamera # most likely app to have
ax layout_bounds show
ax layout_bounds hide
ax list_packages
ax max_bright
ax permissions com.android.settings
ax pull_apks com.android.settings ~/temp
ax screenshot
ax settings_app
ax version_name com.android.settings
ax disable_audio voice_call
ax disable_audio system
ax disable_audio ring
ax disable_audio music
ax disable_audio alarm
ax disable_audio notification
ax disable_audio dtmf
ax disable_audio accessibility
ax night_mode on
ax night_mode off
ax night_mode auto
ax display
ax processor
ax talkback on
sleep 3
ax talkback off
ax font_scale small
ax font_scale default
ax font_scale large
ax font_scale largest
ax font_scale default
ax display_scale small
ax display_scale default
ax display_scale large
ax display_scale larger
ax display_scale largest
ax display_scale default
ax reboot
